name: builder

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: clone unit repo
        run: git clone -b branches/packaging https://github.com/nginx/unit.git

      - name: build container
        run: |
          cd unit/pkg/docker
          make build-python3.8 VERSION_python=3.8

      - name: registry auth
        run: echo "${{github.token}}" | docker login https://docker.pkg.github.com -u ${{github.actor}} --password-stdin

      - name: tag and push
        run: |
          cd unit
          source version
          TAG=${NXT_VERSION}-python3.8
          IMAGE=docker.pkg.github.com/${{github.repository}}/unit
          docker tag unit:${TAG} ${IMAGE}:${TAG}
          docker tag unit:${TAG} ${IMAGE}:latest-python3.8
          docker push --all-tags ${IMAGE}
